version: 0.2
phases:
  install:   
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://anotherbucket222222222/folder/
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
