version: 0.2
phases: 
  install:
    runtime-versions: 
      nodejs: 18
  prebuild:
    commands:
      - npm install
  build: 
    commands: 
      - npm build 

artifacts: 
  files: 
    - "**/*"
  base-directory: "dist"

